# Generated by Django 4.2.17 on 2024-12-22 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dispositivo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='devicemodel',
            name='serial',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
