# Generated by Django 4.2.17 on 2024-12-29 03:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dispositivo', '0004_imagenusuario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagenusuario',
            name='imagen',
            field=models.ImageField(upload_to='fotos_perfil/'),
        ),
    ]
