# Generated by Django 4.2.17 on 2025-01-30 01:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dispositivo', '0007_profile_bio_profile_direccion_profile_telefono'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='departamento',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
