# Generated by Django 4.2.17 on 2025-02-03 02:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dispositivo', '0008_profile_departamento'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='devicemodel',
            options={'permissions': [('visualizar_listado', 'Puede visualizar el listado de productos')]},
        ),
        migrations.AlterField(
            model_name='devicemodel',
            name='serial',
            field=models.CharField(default='', editable=False, max_length=20, unique=True),
        ),
    ]
