# Generated by Django 4.2.17 on 2025-02-05 02:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dispositivo', '0009_alter_devicemodel_options_alter_devicemodel_serial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='rut',
            field=models.CharField(blank=True, max_length=12, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='devicemodel',
            name='estado',
            field=models.CharField(choices=[('Disponible', 'Disponible'), ('No Disponible', 'No Disponible'), ('Prestado', 'Prestado'), ('Mantenimiento', 'Mantenimiento')], default='Disponible', max_length=50),
        ),
        migrations.AlterField(
            model_name='devicemodel',
            name='stock',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
