# Generated by Django 4.2.17 on 2025-02-24 01:35

import dispositivo.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dispositivo', '0010_profile_rut_alter_devicemodel_estado_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='rut',
            field=models.CharField(max_length=12, validators=[dispositivo.models.validar_rut]),
        ),
    ]
