# Generated by Django 4.2.17 on 2025-02-24 01:36

import dispositivo.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dispositivo', '0011_alter_profile_rut'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='rut',
            field=models.CharField(max_length=12, unique=True, validators=[dispositivo.models.validar_rut]),
        ),
    ]
