# Generated by Django 4.2.17 on 2024-12-25 04:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('producto', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='producto',
            options={'permissions': [('visualizar_listado', 'Puede visualizar el listado de productos')]},
        ),
    ]
