# Generated by Django 4.2.17 on 2024-12-29 03:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('producto', '0002_alter_producto_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='prestamo',
            name='notificacion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='producto.notificacion'),
        ),
    ]
