# Generated by Django 4.2.17 on 2025-01-30 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('producto', '0004_bodega_prestamo_bodega_producto_bodega'),
    ]

    operations = [
        migrations.AddField(
            model_name='notificacion',
            name='cantidad',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
