# Generated by Django 4.2.17 on 2025-01-31 00:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('producto', '0006_producto_numero_serie_alter_notificacion_cantidad'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='tipo_descripcion',
            field=models.CharField(blank=True, choices=[('dirección', 'Dirección'), ('docente', 'Docente'), ('alumno', 'Alumno'), ('auxiliar', 'Auxiliar'), ('administrativo', 'Administrativo'), ('pie', 'Pie'), ('convivencia escolar', 'Convivencia escolar')], max_length=20, verbose_name='Tipo de descripción'),
        ),
    ]
