# Generated by Django 4.2.17 on 2025-01-31 01:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('producto', '0007_producto_tipo_descripcion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='tipo_descripcion',
            field=models.CharField(blank=True, choices=[('aseo', 'Aseo'), ('oficina', 'Oficina'), ('ferretería', 'Ferretería'), ('lab_electronica', 'Lab_Electronica'), ('lab_telecomunicaciones', 'Lab_Telecomunicaciones'), ('herramientas', 'Herramientas'), ('toner_tintas', 'Toner_Tintas')], max_length=50, verbose_name='Tipo de descripción'),
        ),
    ]
