# Generated by Django 4.2.17 on 2025-01-31 01:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('producto', '0008_alter_producto_tipo_descripcion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='tipo_descripcion',
            field=models.CharField(blank=True, choices=[('Aseo', 'Aseo'), ('Oficina', 'Oficina'), ('Ferretería', 'Ferretería'), ('Lab_Electronica', 'Lab_Electronica'), ('Lab_Telecomunicaciones', 'Lab_Telecomunicaciones'), ('Herramientas', 'Herramientas'), ('Toner_Tintas', 'Toner_Tintas')], max_length=50, verbose_name='Tipo de descripción'),
        ),
    ]
