# Generated by Django 4.2.17 on 2025-03-19 01:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('producto', '0010_producto_imagen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='imagen',
            field=models.ImageField(blank=True, default='productos/default-placeholder.png', null=True, upload_to='productos/'),
        ),
    ]
