# Generated by Django 4.2.17 on 2025-04-09 01:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('producto', '0011_alter_producto_imagen'),
    ]

    operations = [
        migrations.AddField(
            model_name='bodega',
            name='tipo_bodega',
            field=models.CharField(blank=True, choices=[('Pañol', 'Pañol'), ('Bodega Audio', 'Bodega Audio')], max_length=50, verbose_name='Tipo de bodega'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='imagen',
            field=models.ImageField(default='productos/default-placeholder.png', upload_to='productos/'),
        ),
    ]
